---
- name: Running From My GitHub Repository
  hosts: all
  gather_facts: false

  tasks:
    - name: Show IOS Version & Show Route
      ios_command:
        commands:
         - show ip int brief | ex un
         - show ip eigrp interface
         - ping 172.16.1.1

      register: output
    - debug: var=output.stdout_lines

