---
- name: Getting Started With Automation
  hosts: all
  gather_facts: false

  tasks:
    - name: SHOW COMMANDS
      ios_command:
        commands:
         - show ver | sec IOS
         - show ip int brief 
         - show ip arp
      register: output
    - debug: var=output.stdout_lines

