---
- name: Example of facts being pushed right back to device.
  hosts: rtrs
  gather_facts: false
  tasks:
    - name: grab arista eos facts
      ios_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces

- name: Ensure that the IP address information is accurate.
  ios_l3_interfaces:
    config: "{{ ansible_network_resources['l3_interfaces'] }}"
    register: result

- name: Ensure config did not change.
  assert:
    that: not result.changed


        
     #register: output
  # - debug: var=output.stdout_lines

