---
- name: Running From My GitHub Repository
  hosts: all
  gather_facts: false

  tasks:
    - name: Show IOS Version & Show Route
      ios_command:
        commands:
         - show ip int brief 
         - show run | sec router
      register: output
    - debug: var=output.stdout_lines

