---
- name: configure interfaces on cisco dmvpn rtrs
  hosts: rtrs
 # gather_facts: false

  tasks:
    cisco.ios.ios_l3_interfaces:
      config:
      - name: Loopback100
        ipvv4:
        - address: 100.100.100.1/24
        
     #register: output
  # - debug: var=output.stdout_lines

