---
routers:
  hosts:
    HUB:
      ansible_host: 172.16.1.2
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_user: admin
      ansible_password: admin
      ansible_python_interpreter: /usr/bin/python3